### PR TITLE
Adding TypeScript support

### PR DESCRIPTION
**Pull request by evanshortiss**
Hi @mjesuele, thanks for this module.

I've been getting it up and running with TypeScript and needed some definitions to get started. They are not complete yet, but I'm opening this PR so you can confirm if you'd merge these or not. If not, then I will add them to DefinitelyTyped.

### CODE REVIEW

**Comment by mjesuele** [comment]
Hi @evanshortiss -- thanks for your contribution! I'd love to support TypeScript. Is this mergeable now or should I wait for more from you?

**Comment by evanshortiss** [comment]
@mjesuele, awesome! Not ready just yet, will @ you once it's updated 👍

**Comment by evanshortiss** [comment]
@mjesuele should be covered now 👍

**Comment by evanshortiss** [comment]
Actually. Going to test a little more.

**Comment by evanshortiss** [comment]
@mjesuele should be all good now!

**Comment by mjesuele** [comment]
@evanshortiss fantastic, thanks for this! merging now.

**Pull request merged**
